#!/usr/bin/env python3

# F-Droid repository configuration for Miles Client

# Repository metadata
repo_url: "https://mujehoxe.github.io/miles-client"
repo_name: "Miles Client F-Droid Repository"
repo_icon: "fdroid-icon.png"
repo_description: "F-Droid repository for Miles Client - Location tracking and management app"

# Repository configuration
archive_older: 2  # Keep 2 older versions
make_current_version_link: true
update_stats: true

# Build configuration  
accepted_formats:
  - apk

# Keystore configuration (will be handled in CI/CD)
keystore: "miles-client-keystore.jks"
keystorepass: "env:KEYSTORE_PASS"
keyalias: "milesclient"
keypass: "env:KEY_PASS"

# App-specific configuration
apps:
  - 
    id: "com.mujeorg.milesclient"
    name: "Miles Client"
    summary: "Location tracking and management app"
    description: |
      Miles Client is a comprehensive location tracking and management application 
      that helps users track their activities, manage campaigns, and monitor their progress.
      
      Features:
      - Real-time location tracking
      - Campaign management
      - Progress monitoring
      - Offline support
      - Push notifications
      
    license: "Unknown"  # Please update with your actual license
    categories:
      - "Navigation"
      - "Sports & Health"
    website: "https://github.com/mujehoxe/miles-client"
    source_code: "https://github.com/mujehoxe/miles-client"
    issue_tracker: "https://github.com/mujehoxe/miles-client/issues"
    donate: ""  # Add if you accept donations
    
    # Build configuration
    builds:
      - versionName: "1.0.0"
        versionCode: 1
        commit: "main"
        gradle:
          - "yes"
        output: "app/build/outputs/apk/release/app-release.apk"