name: EAS Build

on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [android, ios]
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Determine build profile
        id: build-profile
        run: |
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            echo "profile=production" >> $GITHUB_OUTPUT
            echo "Building for production (tagged release)"
          elif [[ $GITHUB_REF == refs/heads/main ]]; then
            echo "profile=preview" >> $GITHUB_OUTPUT
            echo "Building preview for main branch"
          elif [[ $GITHUB_REF == refs/heads/develop ]]; then
            echo "profile=staging" >> $GITHUB_OUTPUT
            echo "Building staging for develop branch"
          else
            echo "profile=development" >> $GITHUB_OUTPUT
            echo "Building development for feature branch"
          fi

      - name: Build on EAS
        run: |
          if [ "${{ matrix.platform }}" = "ios" ]; then
            # Only build iOS for production tags to save free tier builds
            if [[ "${{ steps.build-profile.outputs.profile }}" == "production" ]] || [[ "${{ steps.build-profile.outputs.profile }}" == "preview" ]]; then
              eas build --platform ios --profile ${{ steps.build-profile.outputs.profile }} --non-interactive --no-wait
            else
              echo "Skipping iOS build for ${{ steps.build-profile.outputs.profile }} to conserve free tier builds"
            fi
          else
            eas build --platform android --profile ${{ steps.build-profile.outputs.profile }} --non-interactive --no-wait
          fi

      - name: Create deployment summary
        run: |
          echo "## 🚀 Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Platform**: ${{ matrix.platform }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Profile**: ${{ steps.build-profile.outputs.profile }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Branch/Tag**: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Check your build status at: https://expo.dev/accounts/muje-org/projects/miles-client/builds" >> $GITHUB_STEP_SUMMARY

  # Optional: Submit to app stores for production builds
  submit:
    name: Submit to App Stores
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      # Uncomment when you're ready to auto-submit to stores
      # - name: Submit to App Stores
      #   run: |
      #     eas submit --platform all --profile production --non-interactive --wait